#Умная ванна: Управление и сенсоры
#Шаблоны https://www.home-assistant.io/docs/configuration/templating/
#MQTT HVAC https://www.home-assistant.io/integrations/climate.mqtt/
#MQTT Switch https://www.home-assistant.io/integrations/switch.mqtt/
#Template Light https://www.home-assistant.io/integrations/light.template/
#Lovelace Thermostat Card https://github.com/fineemb/lovelace-thermostat-card
#Lovelace Mushroom https://github.com/piitaya/lovelace-mushroom
#Lovelace Flex horseshoe card https://github.com/AmoebeLabs/flex-horseshoe-card
#Lovelace Lovelace layout card https://github.com/thomasloven/lovelace-layout-card


################################ Сенсоры ################################
sensor:
#Целевая температура
#Объект: sensor.smartbath_electric_drive_difference_between_current_and_target_water_temperature
  - platform: template
    sensors:
      smartbath_electric_drive_difference_between_current_and_target_water_temperature:
        friendly_name: "Сенсор: Целевая температура"
        icon_template: mdi:coolant-temperature
        value_template: >
            {% set current_temperature = states('sensor.smartbath_water_temperature') %}
            {% set target_temperature = state_attr('climate.smartbath_electric_drive_target_water_temperature','temperature') %}
            {% set sum = current_temperature|float(0)|round(0) - target_temperature|float(0)|round(0) %}
            {{ sum | abs }}

#Вращение мотора
#Объект: sensor.smartbath_electric_drive_decrease_or_increase_in_water_temperature
      smartbath_electric_drive_decrease_or_increase_in_water_temperature:
        friendly_name: "Сенсор: Смешивание воды"
        icon_template: mdi:poker-chip
        value_template: >
            {% set current_temperature = states('sensor.smartbath_current_water_temperature') %}
            {% set target_temperature = state_attr('climate.smartbath_electric_drive_target_water_temperature','temperature') %}
            {% set sum = target_temperature|float(0)|round(0) - current_temperature|float(0)|round(0) %}
            {% if sum + 1 == 0 or sum - 1 == 0 or sum == 0 %} Комфорт
            {% elif sum + 1 < 0 %} Холоднее
            {% elif sum - 1 > 0 %} Горячее
            {% endif %}


#Отслеживаем статус 8-канального реле zigbee, доступен или недоступен
  - platform: template
    sensors:
      smartbath_controller_online_status:
        friendly_name: 'Умная ванна: Контроллер. Статус в сети'
        icon_template: mdi:access-point-network
        value_template: >
            {% set last_seen = (as_timestamp(now()) - as_timestamp(states('sensor.smartbath_controller_last_seen')))|int %}
            {% if last_seen > 7 %} offline
            {% elif last_seen < 7 %} online
            {% endif %}



################################ MQTT HVAC ################################
#Электропривод: Температура воды
#Объект: climate.smartbath_electric_drive_target_water_temperature
mqtt:
  climate:
    - unique_id: climate smartbath electric drive target water temperature
      object_id: smartbath electric drive target water temperature
      name: "Термостат: Температура воды"
      modes: ["off", "auto"]
      mode_command_topic: "custom_entities/bathroom/smartbath/mode/set"
      temperature_command_topic: "custom_entities/bathroom/smartbath/temperature/target"
      current_temperature_topic: "homed/fd/zigbee/SmartBath: Relay Controller/12"
      value_template: >
        {{ value_json.temperature }}
      min_temp: 20
      max_temp: 60
      temp_step: 1
      precision: 0.1
      qos: 0
      retain: true
      icon: mdi:thermostat

################################ MQTT Switch ################################
#Электропривод: Смешивание воды
#Объект: switch.smartbath_electric_drive_mixing_water
  switch:
    - unique_id: switch smartbath electric drive mixing water
      object_id: smartbath electric drive mixing water
      name: "Выключатель: Смешивание воды"
      command_topic: "custom_entities/bathroom/smartbath/mode/set"
      state_topic: "custom_entities/bathroom/smartbath/mode/set"
      payload_on: "auto"
      payload_off: "off"
      qos: 0
      retain: true
      icon: mdi:poker-chip

#Умная ванна: Контроллер
#Объект: sensor.smartbath_controller_online_status_homed
  sensor:
    - name: "Умная ванна: Контроллер. Статус в сети. Homed"
      unique_id: smartbath controller online status homed
      object_id: smartbath controller online status homed
      state_topic: "homed/device/zigbee/SmartBath: Relay Controller"
      value_template: "{{ value_json.status }}"
      qos: 0
      icon: mdi:access-point-network

################################ Вспомогательные элементы ################################
input_boolean:
#Задержка включения электропривода
#Объект: input_boolean.smartbath_electric_drive_delay_on_off
  smartbath_electric_drive_delay_on_off:
    name: "Задержка включения электропривода"
    icon: mdi:camera-timer

#Режим работы ванны: автоматически или вручную
#Объект: input_boolean.smartbath_auto_or_manual_mode
  smartbath_auto_or_manual_mode:
    name: "Умная ванна: Режим работы. Авто или вручную"
    icon: mdi:thermostat-auto

#Умная ванна: Датчик воды 1. Перекрыть воду
#Объект: input_boolean.smartbath_water_sensor_1_shut_off_water
  smartbath_water_sensor_1_shut_off_water:
    name: "Умная ванна: Датчик воды 1. Перекрыть воду"
    icon: mdi:thermostat-auto

#Умная ванна: Голосовая активация умной ванны
#Объект: input_boolean.smartbath_voice_activation_of_the_smartbath
  smartbath_voice_activation_of_the_smartbath:
    name: "Умная ванна: Голосовая активация умной ванны"
    icon: mdi:account-voice

#Текущая температура воды
#Объект: input_number.smartbath_electric_drive_target_water_temperature
input_number:
  smartbath_electric_drive_target_water_temperature:
    name: "Текущая температура воды"
    min: 0
    max: 100
    step: 1
    mode: box
    unit_of_measurement: °C
    icon: mdi:coolant-temperature

#Задержка включения сервопривода
#Объект: input_number.smartbath_electric_drive_start_delay
  smartbath_electric_drive_start_delay:
    name: "Задержка включения сервопривода"
    min: 0
    max: 1000
    step: 1
    mode: box
    icon: mdi:camera-timer

#Напор воды. История
#Объект: input_number.smartbath_water_pressure_adjustment_history
  smartbath_water_pressure_adjustment_history:
    name: "Напор воды. История"
    min: 0
    max: 100
    step: 1
    mode: box
    icon: mdi:water-pump

#Напор воды. Выбор цвета h
#Объект: input_number.smartbath_color_h_input
  smartbath_color_h_input:
    name: "Напор воды. Выбор цвета h"
    min: 0
    max: 1000
    step: 1
    mode: box
    icon: mdi:palette

#Напор воды. Выбор цвета h
#Объект: input_number.smartbath_color_s_input
  smartbath_color_s_input:
    name: "Напор воды. Выбор цвета s"
    min: 0
    max: 1000
    step: 1
    mode: box
    icon: mdi:palette

#Мойка ванны: Количество моек ванны
#Объект: counter.smartbath_automatic_bath_washing_counter
counter:
  smartbath_automatic_bath_washing_counter:
    name: "Мойка ванны: Количество моек ванны"
    initial: 0
    step: 1
    icon: mdi:counter

################################ Освещение ################################
#Умная ванна: Напор воды
#Объект: light.smartbath_water_pressure_adjustment
light:
  - platform: template
    lights:
      smartbath_water_pressure_adjustment:
        friendly_name: "Умная ванна: Напор воды"
        icon_template: mdi:water-pump
        level_template: "{{ states('number.smartbath_water_pressure_adjustment')|int*2.55 }}"
        color_template: "({{states('input_number.smartbath_color_h_input') | int}}, {{states('input_number.smartbath_color_s_input') | int}})"
        turn_on:
          service: number.set_value
          data:
            value: "{{ states('input_number.smartbath_water_pressure_adjustment_history')|int }}"
          target:
            entity_id: number.smartbath_water_pressure_adjustment
        turn_off:
          - service: input_number.set_value
            data:
              value: "{{ states('number.smartbath_water_pressure_adjustment') }}"
            target:
              entity_id: input_number.smartbath_water_pressure_adjustment_history
          - service: number.set_value
            data:
              value: 0
            target:
              entity_id: number.smartbath_water_pressure_adjustment
        set_level:
          service: number.set_value
          data:
            value: "{{ (brightness|float /2.55) | int }}"
          target:
            entity_id: number.smartbath_water_pressure_adjustment
        set_color:
          - service: input_number.set_value
            data:
              value: "{{ h }}"
              entity_id: input_number.smartbath_color_h_input
          - service: input_number.set_value
            data:
              value: "{{ s }}"
              entity_id: input_number.smartbath_color_s_input


